### ISSUE TITLE
Get an error "Uncaught Error: Cannot find module '../imports/ui/body.js'"

### ISSUE THREAD

**Issue by TimFargloom** [TimFargloom/simple-todos#1]
1. try to remove and add blaze-html-teamplates
(doesn't work)
2. import statement is in client/main.js
3. imports folder typed correctly
4. import statement typed correctly
5. add <body> tag (doen't work)

**Comment by TimFargloom** [comment]
Maybe its the version of Meteor??

**Comment by TimFargloom** [comment]
@pauldulong help :)

**Comment by pauldulong** [comment]
Looks like a simple issue with the path, it can't locate the file. Don't think it's a versioning/plugin issue. On which file this gets triggered @TimFargloom

**Comment by TimFargloom** [comment]
body.js

**Comment by TimFargloom** [comment]
Solved! I created body.js in imports instead of imports/ui. Stupid...
